public enum TaskType {
    BEKLEME,
    SIPARISALMA,
    SIPARISGOTURME,
    HESAPGOTURME,
    DOGRAMA,
    FIRINLAMA,
    HASLAMA,
    TABAKLAMA,
    KIZARTMA,

    MASASILME,
    YERSILME,
    ICECEKGETIRME,
    CAYHAZIRLAMA,
    KAHVEHAZIRLAMA,
    KOKTEYLHAZIRLAMA,
    OCAKSILME,
    TEZGAHSILME,
    BULASIKYIKAMA,
    SOSHAZIRLAMA,
    

}